# 👇 Archivo .yml de configuracion para Docker
version: '3.3'

services:
  postgres: # 👈 Persistencia de Base de dato Postgres para NestJS
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin: # 👈 PGAdmin interfaz para base de datos Postgres
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mysql: # 👈 Persistencia de Base de dato MySql para NestJS
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_db
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin: # 👈 PHPMyAadmin interfaz para base de datos MySql
    image: phpmyadmin/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - PMA_HOST=mysql
    ports:
      - '8081:80'
    depends_on:
      - mysql
