# 👇 Archivo .yml de configuracion para Docker
version: '3.3'

services:
  postgres: # 👈 Base de dato Postgres para NestJS
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin: # 👈 PGAdmin interfaz para base de datos Postgres
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
